### ISSUE TITLE
WIP [FEATURE] - Multischeme file ingestion

### ISSUE THREAD

**Issue by hayssams** [ebiznext/comet-data-pipeline#476]
## Description
We may sometimes need to split files among multiple tables during ingestion depending on a column value.
For DSV files, this means that when a column matches  particular regex, we may simply decide to ingest selected fields in specific tables
For Position based files, this means that when the line matches a specific prefix, we may decide to ingest specific fields at specific positions (positions may vary depending on the matched prefix) in specific tables.

We may even be willing to put put all the fields in the same table creating a sparse table where many columns may be null.

## Solution proposition
A new section called chewer will define the splitting strategy as follows:
```
 
schemas:
  chewer:
    strategy1:
       line:^AB.*$
    strategy2:
      line:^CD.*$
  name: my_table
  attributes:
    - name: col1
      strategy: strategy1
    - name:col2
      strategy: strategy2

```

In the example above, lines starting with AB will only fill col1 in the table and lines starting with CD will only fill col2 in the table

To split the file among multiple tables we move up the chewer section in the hierarchy and override the schema name for those fields as follows:
```
 
chewer:
  strategy1:
     line:^AB.*$
     name: 
  strategy2:
    line:^CD.*$
schemas:
  name: my_table
  attributes:
    - name: col1
      strategy: strategy1
    - name:col2
      strategy: strategy2

```

## Additional context
This could include:
- Design diagrams
- Documentation draft
- Migration strategy
- Adoption and teachability for this feature

# Life cycle

## Possible implementation
Describe here a brief for any contributor wishing to work on this issue

## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.
Don't forget to tag this issue as a 'good first issue' if you think it is appropriate!
